package impuestos;
/**
* serviciosimpuestosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serviciosimpuestos.idl
* lunes 1 de julio de 2019 09H37' BOT
*/

public final class serviciosimpuestosHolder implements org.omg.CORBA.portable.Streamable
{
  public serviciosimpuestos value = null;

  public serviciosimpuestosHolder ()
  {
  }

  public serviciosimpuestosHolder (serviciosimpuestos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serviciosimpuestosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serviciosimpuestosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serviciosimpuestosHelper.type ();
  }

}
