package impuestos;
/**
* serviciosimpuestosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serviciosimpuestos.idl
* lunes 1 de julio de 2019 09H37' BOT
*/

public abstract class serviciosimpuestosPOA extends org.omg.PortableServer.Servant
 implements serviciosimpuestosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calcularimpuesto", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // serviciosimpuestos/calcularimpuesto
       {
         int importe = in.read_long ();
         String $result = null;
         $result = this.calcularimpuesto (importe);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:serviciosimpuestos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public serviciosimpuestos _this() 
  {
    return serviciosimpuestosHelper.narrow(
    super._this_object());
  }

  public serviciosimpuestos _this(org.omg.CORBA.ORB orb) 
  {
    return serviciosimpuestosHelper.narrow(
    super._this_object(orb));
  }


} // class serviciosimpuestosPOA
