package impuestos;
/**
* serviciosimpuestos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serviciosimpuestos.idl
* lunes 1 de julio de 2019 09H37' BOT
*/

public interface serviciosimpuestos extends serviciosimpuestosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface serviciosimpuestos
