package impuestos;
/**
* serviciosimpuestosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serviciosimpuestos.idl
* lunes 1 de julio de 2019 09H37' BOT
*/

public interface serviciosimpuestosOperations 
{
  String calcularimpuesto (int importe);
} // interface serviciosimpuestosOperations
