
package wsbanco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsBanco", targetNamespace = "http://wsBanco/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBanco {


    /**
     * 
     * @param fecha
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "ObtenerCotizacion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ObtenerCotizacion", targetNamespace = "http://wsBanco/", className = "wsbanco.ObtenerCotizacion")
    @ResponseWrapper(localName = "ObtenerCotizacionResponse", targetNamespace = "http://wsBanco/", className = "wsbanco.ObtenerCotizacionResponse")
    @Action(input = "http://wsBanco/wsBanco/ObtenerCotizacionRequest", output = "http://wsBanco/wsBanco/ObtenerCotizacionResponse")
    public Double obtenerCotizacion(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha);

}
