package sisbancocompleto;
/**
* _servicioscotesStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* domingo 30 de junio de 2019 08H35' BOT
*/

public class _servicioscotesStub extends org.omg.CORBA.portable.ObjectImpl implements servicioscotes
{

  public String facturaspendientes (int numero, String llave)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("facturaspendientes", true);
                $out.write_long (numero);
                $out.write_string (llave);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return facturaspendientes (numero, llave        );
            } finally {
                _releaseReply ($in);
            }
  } // facturaspendientes

  public String pagar (int idfactura, String llave)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pagar", true);
                $out.write_long (idfactura);
                $out.write_string (llave);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pagar (idfactura, llave        );
            } finally {
                _releaseReply ($in);
            }
  } // pagar

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servicioscotes:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _servicioscotesStub
