package sisbancocompleto;
/**
* servicioscotesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* domingo 30 de junio de 2019 08H35' BOT
*/

public final class servicioscotesHolder implements org.omg.CORBA.portable.Streamable
{
  public servicioscotes value = null;

  public servicioscotesHolder ()
  {
  }

  public servicioscotesHolder (servicioscotes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servicioscotesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servicioscotesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servicioscotesHelper.type ();
  }

}
