package sisbancocompleto;
/**
* servicioscotesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* domingo 30 de junio de 2019 08H35' BOT
*/

public interface servicioscotesOperations 
{
  String facturaspendientes (int numero, String llave);
  String pagar (int idfactura, String llave);
} // interface servicioscotesOperations
