package sisbancocompleto;
/**
* servicioscotes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* domingo 30 de junio de 2019 08H35' BOT
*/

public interface servicioscotes extends servicioscotesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface servicioscotes
