package sisbancocompleto;
/**
* servicioscotesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cotes.idl
* domingo 30 de junio de 2019 08H35' BOT
*/

public abstract class servicioscotesPOA extends org.omg.PortableServer.Servant
 implements servicioscotesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("facturaspendientes", new java.lang.Integer (0));
    _methods.put ("pagar", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servicioscotes/facturaspendientes
       {
         int numero = in.read_long ();
         String llave = in.read_string ();
         String $result = null;
         $result = this.facturaspendientes (numero, llave);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // servicioscotes/pagar
       {
         int idfactura = in.read_long ();
         String llave = in.read_string ();
         String $result = null;
         $result = this.pagar (idfactura, llave);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servicioscotes:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public servicioscotes _this() 
  {
    return servicioscotesHelper.narrow(
    super._this_object());
  }

  public servicioscotes _this(org.omg.CORBA.ORB orb) 
  {
    return servicioscotesHelper.narrow(
    super._this_object(orb));
  }


} // class servicioscotesPOA
