
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsDeudas", targetNamespace = "http://servicios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsDeudas {


    /**
     * 
     * @param idcliente
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDeuda", targetNamespace = "http://servicios/", className = "servicios.ObtenerDeuda")
    @ResponseWrapper(localName = "obtenerDeudaResponse", targetNamespace = "http://servicios/", className = "servicios.ObtenerDeudaResponse")
    @Action(input = "http://servicios/wsDeudas/obtenerDeudaRequest", output = "http://servicios/wsDeudas/obtenerDeudaResponse")
    public int obtenerDeuda(
        @WebParam(name = "idcliente", targetNamespace = "")
        int idcliente);

}
