
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsDeudas", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:20476/Deudas/wsDeudas?wsdl")
public class WsDeudas_Service
    extends Service
{

    private final static URL WSDEUDAS_WSDL_LOCATION;
    private final static WebServiceException WSDEUDAS_EXCEPTION;
    private final static QName WSDEUDAS_QNAME = new QName("http://servicios/", "wsDeudas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20476/Deudas/wsDeudas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDEUDAS_WSDL_LOCATION = url;
        WSDEUDAS_EXCEPTION = e;
    }

    public WsDeudas_Service() {
        super(__getWsdlLocation(), WSDEUDAS_QNAME);
    }

    public WsDeudas_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDEUDAS_QNAME, features);
    }

    public WsDeudas_Service(URL wsdlLocation) {
        super(wsdlLocation, WSDEUDAS_QNAME);
    }

    public WsDeudas_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDEUDAS_QNAME, features);
    }

    public WsDeudas_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDeudas_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsDeudas
     */
    @WebEndpoint(name = "wsDeudasPort")
    public WsDeudas getWsDeudasPort() {
        return super.getPort(new QName("http://servicios/", "wsDeudasPort"), WsDeudas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDeudas
     */
    @WebEndpoint(name = "wsDeudasPort")
    public WsDeudas getWsDeudasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "wsDeudasPort"), WsDeudas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDEUDAS_EXCEPTION!= null) {
            throw WSDEUDAS_EXCEPTION;
        }
        return WSDEUDAS_WSDL_LOCATION;
    }

}
